### ISSUE TITLE
Forking and cloning via GitHub Desktop issue

### ISSUE THREAD

**Issue by rogadev** [jurassicjs/avantage#1]
I went ahead and forked the repo and tried to open it up in VS Code on my machine but experienced the following issue:

```
Cloning into 'E:\LocalDevelopmentFiles\nuxt-auth'...
remote: Enumerating objects: 149, done.        
remote: Counting objects: 100% (149/149), done.        
remote: Compressing objects: 100% (130/130), done.        
remote: Total 149 (delta 7), reused 133 (delta 5), pack-reused 0        
Receiving objects: 100% (149/149), 304.13 KiB | 1001.00 KiB/s, done.
Resolving deltas: 100% (7/7), done.
error: invalid path 'public/img/logo-shadow.svg:Zone.Identifier'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

Wondering if you have any ideas. I would try via command line but I'm not very command line savvy. I wouldn't even know where to start. Any ideas?

**Comment by rohrig** [comment]
After a bit of scratching my head and rebasing I re-read the error message and as usual the answer is there. 

The problem was this file public/img/logo-shadow.svg:Zone.Identifier

The path is invalid. I think it was created automatically and I overlooked it. 

Everything should be working now. 

Thanks for opening the issue.
